{
    'name': 'Rok Health',
    'summary': 'Health module for the Rok Project',
    'category': 'Productivity/Health',
    'version': '1.0',
    'depends': [
        'base',
        'rok_spreadsheet',
        'spreadsheet_dashboard',
        'account',
    ],
    'data': [
        'data/product_category.xml',
        'security/ir.model.access.csv',
        'security/rok_health_rules.xml',
        'views/account_move_line.xml',
        'views/anthropometry_views.xml',
        'views/calories_views.xml',
        'views/dashboard_anthropometry.xml',
        'views/product_product.xml',
    ],
    'installable': True,
    'application': False,
    'author': 'Ruslan Akunevich',
    'license': 'LGPL-3',
}
