{
    "name": "Rok Health",
    "summary": "Health module for the Rok Project",
    "category": "Productivity/Health",
    "version": "2.0",
    "depends": [
        "product",
        "account",
        "rok_apps",
    ],
    "data": [
        "data/product_category.xml",
        "data/rok_apps.xml",
        "security/ir.model.access.csv",
        "security/anthropometry_security.xml",
        "security/calories_security.xml",
        "views/account_move_line.xml",
        "views/anthropometry_views.xml",
        "views/calories_views.xml",
        "views/product_product.xml",
    ],
    "installable": True,
    "application": False,
    "author": "Ruslan Akunevich",
    "license": "LGPL-3",
    "assets": {
        "web.assets_backend": [
            "rok_health/static/src/components/anthropometry.js",
            "rok_health/static/src/components/anthropometry.xml",
            "rok_health/static/src/components/anthropometry_toolbar.js",
            "rok_health/static/src/components/anthropometry_toolbar.xml",
            "rok_health/static/src/components/anthropometry_toolbar.scss",
            "rok_health/static/src/rok_apps_widget.js",
            "rok_health/static/src/rok_apps_widget.xml",
            "rok_health/static/src/rok_apps_widget.scss",
        ],
        "web.assets_backend_lazy": [
            "rok_health/static/src/views/graph/anthropometry_graph.js",
            "rok_health/static/src/views/graph/anthropometry_graph.xml",
        ],
    },
}
