{
    "name": "Weather",
    "version": "1.0",
    "summary": "Weather module",
    "author": "Ruslan Akunevich",
    "license": "LGPL-3",
    "website": "https://github.com/ruslan-ok/rok-odoo",
    "application": False,
    "category": "Productivity/Weather",
    "depends": ["web", "rok_apps"],
    "data": [
        "security/ir.model.access.csv",
        "views/weather_views.xml",
        "data/rok_apps.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "weather/static/lib/bootstrap_icons/bootstrap-icons.min.css",
            "weather/static/src/components/weather.scss",
            "weather/static/src/components/colors.js",
            "weather/static/src/components/weather_utils.js",
            "weather/static/src/components/weather_for_the_day/weather_for_the_day.js",
            "weather/static/src/components/weather_for_the_day/weather_for_the_day.xml",
            "weather/static/src/components/weather_for_the_week/weather_for_the_week.js",
            "weather/static/src/components/weather_for_the_week/weather_for_the_week.xml",
            "weather/static/src/components/weather_message/weather_message.js",
            "weather/static/src/components/weather_message/weather_message.xml",
            "weather/static/src/components/weather_now/weather_now.js",
            "weather/static/src/components/weather_now/weather_now.xml",
            "weather/static/src/components/weather.js",
            "weather/static/src/components/weather.xml",
        ],
        "web.assets_backend_lazy": [
            "weather/static/src/views/graph/weather_graph.js",
            "weather/static/src/views/graph/weather_graph.xml",
        ],
    },
}
